export enum ApiErrorMessage {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',

  REPOSITORY_NOT_FOUND = 'REPOSITORY_NOT_FOUND',
  LANGUAGE_NOT_SUPPORTED = 'LANGUAGE_NOT_SUPPORTED',
  DEPENDENCY_FILE_NOT_FOUND = 'DEPENDENCY_FILE_NOT_FOUND',
  REPOSITORY_NOT_SUPPORTED = 'REPOSITORY_NOT_SUPPORTED',
}
